version: "3"
services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/auth/health"]
    environment:
      - SERVER_PORT=8090
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL=false

  postgres:
    image: circleci/postgres:11.6-alpine-ram
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    volumes:
      - ./src/main/resources/db/local/init:/docker-entrypoint-initdb.d:ro

networks:
  hmpps:
