version: "3"
services:

  postgres:
    image: circleci/postgres:11.6-alpine-ram
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    volumes:
      - ./src/main/resources/db/local/init:/docker-entrypoint-initdb.d:ro

networks:
  hmpps:
