notify:
  enabled: false

hmpps-auth:
  baseurl: http://localhost:8090/auth

postgres:
  uri: localhost:5432
  db: preferences
  username: root
  password: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  flyway:
    locations: classpath:db/migration,classpath:db/local