notify:
  enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  datasource:
    #    url: 'jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1'
    url: 'jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;'
