notify:
  enabled: false

postgres:
  uri: localhost:5432
  db: preferences
  username: root
  password: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/local
