version: 2.1

parameters:
  only_pacts:
    type: boolean
    default: false
  pact_consumer_tags:
    type: string
    default: main

orbs:
  hmpps: ministryofjustice/hmpps@2.2
  snyk: snyk/snyk@0.0.12

_snyk_options: &snyk_options
  snyk-scan: true
  snyk-fail-build: true
  snyk-args: --policy-path=.snyk --configuration-matching='^((?!test).)*$'

jobs:
  validate:
    executor: hmpps/java
    docker:
      - image: cimg/openjdk:11.0
        environment:
          POSTGRES_DB: circle_test
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: preferences_test
          POSTGRES_PASSWORD: dev
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

  vulnerability_scan:
    executor: hmpps/java
    parameters:
      monitor:
        type: boolean
        default: false
      snyk-scan:
        type: boolean
      snyk-fail-build:
        type: boolean
      snyk-args:
        type: string
    steps:
      - checkout
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}'
          monitor-on-build: << parameters.monitor >>
          organization: "digital-probation-services"
          severity-threshold: "high" # note: this does not affect snyk 'monitor' commands
          fail-on-issues: << parameters.snyk-fail-build >>
          additional-arguments: << parameters.snyk-args >>

  pact_check_and_publish:
    parameters:
      consumer_tags:
        type: string
    environment:
      PACTBROKER_HOST: "pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk"
    executor: hmpps/java
    docker:
      - image: cimg/openjdk:11.0
        environment:
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: |
            PACT_PROVIDER_VERSION="$CIRCLE_SHA1" \
              PACT_PROVIDER_TAG="$CIRCLE_BRANCH" \
              PACTBROKER_CONSUMERVERSIONSELECTORS_TAGS="<< parameters.consumer_tags >>" \
              PACT_PUBLISH_RESULTS="true" \
              ./gradlew pactTestPublish
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
  build-test-and-deploy:
    unless: << pipeline.parameters.only_pacts >>
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          retrieve_secrets: none
          env: "dev"
          helm_additional_args: --values ./hmpps-user-preferences/values-live.yaml
          context:
            - hmpps-common-vars
            - hmpps-user-preferences-live-dev
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          retrieve_secrets: none
          env: "preprod"
          helm_additional_args: --values ./hmpps-user-preferences/values-live.yaml
          context:
            - hmpps-common-vars
            - hmpps-user-preferences-live-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          retrieve_secrets: none
          env: "prod"
          helm_additional_args: --values ./hmpps-user-preferences/values-live.yaml
          slack_channel_name: probation_in_court_dev
          slack_notification: true
          context:
            - hmpps-common-vars
            - hmpps-user-preferences-live-prod
          requires:
            - request-prod-approval
  pact:
    jobs:
      - pact_check_and_publish:
          consumer_tags: << pipeline.parameters.pact_consumer_tags >>

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - vulnerability_scan:
          name: vulnerability_scan_and_monitor
          monitor: true
          <<: *snyk_options
      - hmpps/build_docker:
          publish: false
          <<: *snyk_options
