version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@2.2
  snyk: snyk/snyk@0.0.12

_snyk_options: &snyk_options
  organization: "digital-probation-services"
  severity-threshold: "high" # note: this does not affect snyk 'monitor' commands
  fail-on-issues: true
  additional-arguments: "--policy-path=.snyk"

jobs:
  validate:
    executor: hmpps/java
    docker:
      - image: cimg/openjdk:11.0
        environment:
          POSTGRES_DB: circle_test
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: preferences_test
          POSTGRES_PASSWORD: dev
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

  vulnerability_scan:
    executor: hmpps/java
    parameters:
      monitor:
        type: boolean
        default: false
      snyk-scan:
        type: boolean
      snyk-fail-build:
        type: boolean
      snyk-args:
        type: string
    steps:
      - checkout
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}'
          monitor-on-build: << parameters.main >>
          <<: *snyk_options

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          retrieve_secrets: none
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          retrieve_secrets: none
          env: "preprod"
          context:
            - hmpps-common-vars
            - hmpps-user-preferences-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          retrieve_secrets: none
          env: "prod"
          slack_channel_name: probation_in_court_dev
          slack_notification: true
          context:
            - hmpps-common-vars
            - hmpps-user-preferences-prod
          requires:
            - request-prod-approval

  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - vulnerability_scan:
          name: vulnerability_scan_and_monitor
          monitor: true
          <<: *snyk_options
      - hmpps/build_docker:
          publish: false
          <<: *snyk_options
