apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  selector:
    matchLabels:
  {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "app.name" . }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: hmpps-user-preferences
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.image.port }}
              protocol: TCP

          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL

          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{ .Values.image.port }}
            periodSeconds: 30
            initialDelaySeconds: 90
            timeoutSeconds: 20
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{ .Values.image.port }}
            periodSeconds: 20
            initialDelaySeconds: 60
            timeoutSeconds: 30
            failureThreshold: 15
          {{ if .Values.resources }}
          resources:
            limits:
              cpu: {{ .Values.resources.cpu.limit }}
              memory: {{ .Values.resources.memory.limit }}
            requests:
              cpu: {{ .Values.resources.cpu.request}}
              memory: {{ .Values.resources.memory.request }}
  {{ end }}
  {{ include "deployment.envs" . | nindent 10 }}
