# Per environment values which override defaults in hmpps-template-kotlin/values.yaml

generic-service:
  replicaCount: 2

  podDisruptionBudget:
    enabled: false

  ingress:
    host: hmpps-user-preferences-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SPRINGDOC_API-DOCS_ENABLED: "true"
    SPRINGDOC_SWAGGER-UI_ENABLED: "true"
    SPRING_APPLICATION_JSON: >
      {"hmpps-auth":{"url":"https://sign-in-dev.hmpps.service.justice.gov.uk/auth"}}

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL