create table preference
(
    id            int8 generated by default as identity,
    hmpps_user_id varchar(255) not null,
    name          varchar(255) not null,
    value         varchar(255) not null,
    primary key (id)
)