name: Deploy to QA (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  helm_lint:
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2
    secrets: inherit
    with:
      environment: qa

  build_qa:
    name: Build QA image
    needs: [ helm_lint ]
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2
    secrets: inherit
    with:
      docker_registry: ghcr.io
      registry_org: ministryofjustice
      # Optional but recommended: makes it obvious this is a QA build tag in GHCR
      # additional_docker_tag: qa
      push: true
      docker_multiplatform: false
      download_build_artifacts: false

  deploy_qa:
    name: Deploy to QA
    needs: [build_qa]
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2
    secrets: inherit
    with:
      environment: qa
      app_version: ${{ needs.build_qa.outputs.app_version }}
      slack_notification: "false"
